### ISSUE TITLE
Sponsor

### ISSUE THREAD

**Issue by liamnotenough** [openMLA/photon-ultra-controller-rp2040#2]
​​​Hello
This is Liam from PCBWay.
Deeply impressed by your  project which is novel and creative,
I’d like to sponsor your project by providing free PCB prototyping,
All I ask for in return is a slight promotion or review of our quality or service.
Would you be interested in partnering up? Contact me: liam@pcbway.com

**Comment by NemoAndrea** [comment]
Dear Liam, thank you for offering to sponsor the project. At the moment I think a sponsorship from commercial parties is not the right fit for the project. It is nice, however, to see PCBWay supporting hardware development in general.
